### ISSUE TITLE
Tabs on Bottom not workin properly anymore on FF 119.0

### ISSUE THREAD

**Issue by Sabrehammer** [MrOtherGuy/firefox-csshacks#316]
Tabs are still there, but all white bar with invisible inactive tabs. 

![grafik](https://github.com/MrOtherGuy/firefox-csshacks/assets/114091667/8631b79b-e063-43d2-b8df-5274002b03a9)

**Comment by MrOtherGuy** [comment]
Make sure you are using the latest version of that style.
As far as I can tell, it work without issues in Firefox 119

**Comment by doychi** [comment]
I was using an old version of window_control_placeholder_support.css and needed to update it. After that, things were fixed.

**Comment by MrOtherGuy** [comment]
Alright cool, I'll close this then.

**Comment by Sabrehammer** [comment]
Nope, I added that .css file, but still not working, naked FF 119 only Tabs on bottom code in usercrome.css.

**Comment by MrOtherGuy** [comment]
Oh. Okay, sorry, I didn't notice it was a different person who replied it to be working.

Now that I look your screenshot more closely I have a feeling I know what's going wrong. It seems to me that you are trying to use tabs_on_bottom.css to make tabs appear below content. The purpose of tabs_on_bottom.css is to make tabs the bottom-most toolbar, if you want to move tabs below content then you can use tabs_below_content.css to do so. I just checked and that seems to work correctly in Firefox 119 with several different themes.

**Comment by Sabrehammer** [comment]
My bad, yes I meant tabs_below_bottom.
I figured out what the problem is, I had to change this: 
#TabsToolbar{ background-color: var(--lwt-accent-color); }

to a fixed color instead of accent color.
After this it looks fine again.

No clue about this coding shit as I only use Tabs below content and nothing else in my userCrome.css

Thanks

**Comment by MrOtherGuy** [comment]
I mean, I suppose it might end up transparent if you use some theme that specifically makes sets `--lwt-accent-color` to be transparent. I can't really do anything about that.

**Comment by Sabrehammer** [comment]
See above, figured that out a second ago
Thanks again

**Comment by MrOtherGuy** [comment]
Nice. Btw. could you share what theme you are using? I could add that to the set of themes I test stuff with.

**Comment by Sabrehammer** [comment]
Sure, so I narrowed it down to two things, I'm on Windows 10 where I use the dark color Theme, Transparency on, (but that does not seem to make a difference on FF)
In FF I am on System-Theme, never changed to anything else.

Now, when I use the light Theme on Windows, Tabs look right, and back to dark the bar is gone.
Switching the FF Theme to the dark one fixes it without me having to change the code.

**Comment by MrOtherGuy** [comment]
Okay, sweet. This is something that I actually can fix after all.

**Comment by MrOtherGuy** [comment]
Now with a change from [a0070f7](https://github.com/MrOtherGuy/firefox-csshacks/commit/a0070f74fd16fde78bacff45f5fd1e6d014dd33c) tabs toolbar won't use customized background color when the default theme is being used and thus both dark and light variants of default theme should behave correctly.
